### ISSUE TITLE
[RC] Events

### ISSUE THREAD

**Issue by eliaskaerle** [ODTA/ds#5]
This is the RC (Request for Comments) for the Events RDS. Please use the comments section below for discussions.

Link to RC: https://github.com/ODTA/ds/blob/main/docs/rc/EventDS-RC-RDS.pdf
Link to RC's DS representation: [https://odta.sti2.org/?dsb-list=nAnWVfvH3&dsb-ds=w_YPPr7kF](https://odta.sti2.org/?dsb-list=nAnWVfvH3&dsb-ds=w_YPPr7kF)

**Comment by CF-TMN** [comment]
![image](https://user-images.githubusercontent.com/65600593/199433688-112ce707-3191-4ff6-a0d2-7d4e6b42ef1a.png)
Can the suggestion, to use the advance BookingRequirement-property of offer type in combination with the offers property of Event reflect the situation in a target-oriented way?

How can this requirement in the RDS be specified? (e.g., possible unit codes such as day or hour, specifying minimum or maximum value for the given time unit for advance booking).

**Comment by CF-TMN** [comment]
![image](https://user-images.githubusercontent.com/65600593/199491661-4410618f-8bdb-4b7a-a389-2c78c308a6e7.png)
Please have a look on appendix B, to check if the list of suggested enumeration members is helpful and if there are additional members needed to specify the new property theme and theEventThemeEnumeration enumeration type as its range.

**Comment by tomsievert** [comment]
> 

Test Kommentar

**Comment by tomsievert** [comment]
> ![image](https://user-images.githubusercontent.com/65600593/199433688-112ce707-3191-4ff6-a0d2-7d4e6b42ef1a.png) Can the suggestion, to use the advance BookingRequirement-property of offer type in combination with the offers property of Event reflect the situation in a target-oriented way?
> 
> How can this requirement in the RDS be specified? (e.g., possible unit codes such as day or hour, specifying minimum or maximum value for the given time unit for advance booking).

Test Kommentar

**Comment by CF-TMN** [comment]
![image](https://user-images.githubusercontent.com/65600593/199492993-d7453e05-b9c4-4e5f-aa38-176fb769166d.png)
is "DanceClub" a separate event than a generic dance event? Any opinions?

**Comment by CF-TMN** [comment]
![image](https://user-images.githubusercontent.com/65600593/199494189-60e9bf2e-d5cd-478b-a64d-0658721436d4.png)
![image](https://user-images.githubusercontent.com/65600593/199666820-b4eee3d8-a9d0-4105-b6ff-1e47f3495ee1.png)

- Is "DoItTogetherEvent" the right expression? 
- Is "Mitmachevent" the applicable expression?
- Especially for sports events, a distinction should be made between "watch Sport Event" and "Do sport yourself", as well as "event participation: yes / no".

**Comment by CF-TMN** [comment]
![image](https://user-images.githubusercontent.com/65600593/199495028-1cb9eae8-a148-41e2-bc73-29a87f719ca9.png)
- Is the right translation also "GeneralAssembly"? (label in english)
- Should we call it "Mitgliederversammlung"? (label in german)

**Comment by CF-TMN** [comment]
![image](https://user-images.githubusercontent.com/65600593/199495674-da89531e-ea69-48ca-8b9e-62ac4f5c6ac7.png)
How about "marksmen´s festival"?

**Comment by CF-TMN** [comment]
![image](https://user-images.githubusercontent.com/65600593/199532532-e4a96699-5d32-4bad-97f6-4c0453b46928.png)
Question was: _"How is this different from Lichterfest?"_
**is **"illumination"** the same as **"festival of lights"**?** 
**definition illumination (wikipedia):** "Illumination wird der gezielte Einsatz von Licht für dekorative oder künstlerische Zwecke genannt"
 **definition Lichterfest (wikipedia):** "Lichterfest ist ein Sammelbegriff für ein zeitlich begrenztes Fest, bei dem eine Vielzahl von Lichtquellen, wie beispielsweise Kerzen, Lampen, Lampions, Scheinwerfer, Projektoren und/oder Feuerwerk, im Mittelpunkt stehen und so in der Dämmerung und in der Dunkelheit für eine besondere Atmosphäre sorgen. Eine Weiterentwicklung traditioneller Lichterfeste stellen Luminalen oder Festivals of Lights dar, bei denen die Illumination stadtbildprägender Bauwerke im Vordergrund steht."

**Comment by CF-TMN** [comment]
![image](https://user-images.githubusercontent.com/65600593/199533084-30f4c420-049f-4c66-bcc0-a9e469ac4fbd.png)
Question was: _"is this really a festival?"_
Does "fireworks" fit to the [schema- subclass "festival"](https://schema.org/Festival)?

**Comment by ghost** [comment]
![Finalisierung-Request-for-Comments-Events-–-OneDrive](https://user-images.githubusercontent.com/114583185/199537844-9c073cbc-deeb-43af-92e7-554c00ec3f6e.png)

Questions are: 
**1. How is it different from Weiterbildung?** 
**Answer:** It is difficult, because the english language or translation does not really differ between both*, but:
Continuing education (Fortbildung) refers to a concrete requirement within the framework of current professional/job activities, while further education (Weiterbildung) serves to acquire additional qualifications and is not necessarily directly related to the job currently held.
**2. How should "Fortbildung" be translated and how should the enumeration member be named?** 
Could "training" be the applicable expression or "continuing education"* ? 

*Maybe we have to ask a native speaker :)

**Comment by CF-TMN** [comment]
![image](https://user-images.githubusercontent.com/65600593/199664488-549b8b0a-0ec0-4aa6-a06d-d1f83d2618bb.png)
"Kochwettbewerb"? (label in german)

**Comment by CF-TMN** [comment]
![image](https://user-images.githubusercontent.com/65600593/199664632-60aa5a5d-47de-47a1-b8a2-9de332d9ed2d.png)

- Is a BikeTour in the sense of a guided bike tour a touristtrip or an event? Or is it even an offer?
- Same with "city tour", "bus tour" or "harbour tour". It may be an event in the user context, technically an event and touristtrip or also an offer: how should it be implemented?
- for further information please see: _"Request for Comments for RDS Erweiterungen des Typs TouristTrip und seiner Untertypen  02.02.2022 in [issue#8](https://github.com/ODTA/ds/issues/8)"_

**Comment by CF-TMN** [comment]
![image](https://user-images.githubusercontent.com/65600593/199664777-4a1afa93-d88a-487c-860f-12b89e0a6054.png)
"ship approach"?

**Comment by sumutcan** [comment]
> ![image](https://user-images.githubusercontent.com/65600593/199433688-112ce707-3191-4ff6-a0d2-7d4e6b42ef1a.png) Can the suggestion, to use the advance BookingRequirement-property of offer type in combination with the offers property of Event reflect the situation in a target-oriented way?
> 
> How can this requirement in the RDS be specified? (e.g., possible unit codes such as day or hour, specifying minimum or maximum value for the given time unit for advance booking).

we can use this property in two ways: as a true/false value that only says whether an in advance booking / registration required. In this case just the value property of the QuantitativeValue type would be enough.(true or false). Alternatively, we can use the unitCode to specify how many days/hours/minutes in advance the booking should be done.

**Comment by SunderlandNRW** [comment]
> > ![image](https://user-images.githubusercontent.com/65600593/199433688-112ce707-3191-4ff6-a0d2-7d4e6b42ef1a.png) Can the suggestion, to use the advance BookingRequirement-property of offer type in combination with the offers property of Event reflect the situation in a target-oriented way?
> > How can this requirement in the RDS be specified? (e.g., possible unit codes such as day or hour, specifying minimum or maximum value for the given time unit for advance booking).
> 
> we can use this property in two ways: as a true/false value that only says whether an in advance booking / registration required. In this case just the value property of the QuantitativeValue type would be enough.(true or false). Alternatively, we can use the unitCode to specify how many days/hours/minutes in advance the booking should be done.

I have never really seen an example where it e.g. says "advanced booking required minimum 30 minutes prior" - is that common? We currently only allow a true or false value for advanced booking. Maybe it would be good to add a property "box office" with timing indication e.g. Box office opens 30 minutes before schema:doorTime?

**Comment by SunderlandNRW** [comment]
> ![image](https://user-images.githubusercontent.com/65600593/199492993-d7453e05-b9c4-4e5f-aa38-176fb769166d.png) is "DanceClub" a separate event than a generic dance event? Any opinions?

I feel we need to clarify the difference (or intersections) between nature, theme and types (kindof). And what makes sense all together. 
Looking at the problem "DanceClub" as a type of event (kindof). The event type is DanceEvent. Why do we need more types (kindof)? Wouldn't these new types only be specifications of the existing Type DanceEvent? Properties like "DanceClub" are merely other specifications like those in Annex B (themes). 

I would suggest combining the proposed DS odta:kindOfEvent and odta:theme, as most of the suggested "themes" in Annex B specify MusicEvent anyway. The new DS could be called odta:eventSpecification and list a combination of Annex A and B. An enumeration with minimum one to choose.

However I am not sure if we need to have separate DS odta:eventSpecification for every type of event?
[BusinessEvent](https://schema.org/BusinessEvent) -> odta:eventSpecificationBusiness
[ChildrensEvent](https://schema.org/ChildrensEvent) -> odta:eventSpecificationChildrens
etc.
Or is there a way to cluster a DS odta:eventSpecification with categories and subcategories?

**Comment by SunderlandNRW** [comment]
> ![Finalisierung-Request-for-Comments-Events-–-OneDrive](https://user-images.githubusercontent.com/114583185/199537844-9c073cbc-deeb-43af-92e7-554c00ec3f6e.png)
> 
> Questions are: **1. How is it different from Weiterbildung?** **Answer:** It is difficult, because the english language or translation does not really differ between both*, but: Continuing education (Fortbildung) refers to a concrete requirement within the framework of current professional/job activities, while further education (Weiterbildung) serves to acquire additional qualifications and is not necessarily directly related to the job currently held. **2. How should "Fortbildung" be translated and how should the enumeration member be named?** Could "training" be the applicable expression or "continuing education"* ?
> 
> *Maybe we have to ask a native speaker :)

- Weiterbildung: Further education
- Fortbildung: Professional development

**Comment by SunderlandNRW** [comment]
> ![image](https://user-images.githubusercontent.com/65600593/199495674-da89531e-ea69-48ca-8b9e-62ac4f5c6ac7.png) How about "marksmen´s festival"?

- rifle association festival or rifle club festival

**Comment by SunderlandNRW** [comment]
> ![image](https://user-images.githubusercontent.com/65600593/199494189-60e9bf2e-d5cd-478b-a64d-0658721436d4.png) ![image](https://user-images.githubusercontent.com/65600593/199666820-b4eee3d8-a9d0-4105-b6ff-1e47f3495ee1.png)
> 
> * Is "DoItTogetherEvent" the right expression?
> * Is "Mitmachevent" the applicable expression?
> * Especially for sports events, a distinction should be made between "watch Sport Event" and "Do sport yourself", as well as "event participation: yes / no".

Participative Event?

**Comment by SunderlandNRW** [comment]
> ![image](https://user-images.githubusercontent.com/65600593/199664632-60aa5a5d-47de-47a1-b8a2-9de332d9ed2d.png)
> 
> * Is a BikeTour in the sense of a guided bike tour a touristtrip or an event? Or is it even an offer?
> * Same with "city tour", "bus tour" or "harbour tour". It may be an event in the user context, technically an event and touristtrip or also an offer: how should it be implemented?
> * for further information please see: _"Request for Comments for RDS Erweiterungen des Typs TouristTrip und seiner Untertypen  02.02.2022 in [issue#8](https://github.com/ODTA/ds/issues/8)"_

Maybe there is a need for a DS that indicates the level of activity at an event? -> could be a type of eventParticipation (e.g. Spectating, competiting or contest participating, cycling, walking, etc.) or part of eventNature (active etc.?).

**Comment by SunderlandNRW** [comment]
> ![image](https://user-images.githubusercontent.com/65600593/199491661-4410618f-8bdb-4b7a-a389-2c78c308a6e7.png) Please have a look on appendix B, to check if the list of suggested enumeration members is helpful and if there are additional members needed to specify the new property theme and theEventThemeEnumeration enumeration type as its range.

Once we have decided on the number of RDS, could we list all enumerations in an excel file/ google table to keep an overview of all votes in favour/ against/ comments to specific elements? I feel commenting on all elements that we are not sure with will go beyond githubs comment scope or at least will not help keep an overview on all topics.

**Comment by sumutcan** [comment]
> ![image](https://user-images.githubusercontent.com/65600593/199494189-60e9bf2e-d5cd-478b-a64d-0658721436d4.png) ![image](https://user-images.githubusercontent.com/65600593/199666820-b4eee3d8-a9d0-4105-b6ff-1e47f3495ee1.png)
> 
> * Is "DoItTogetherEvent" the right expression?
> * Is "Mitmachevent" the applicable expression?
> * Especially for sports events, a distinction should be made between "watch Sport Event" and "Do sport yourself", as well as "event participation: yes / no".

if this "participating / watching" distinction is applicable to many event types, we could drop the MitmatchEvent enumeration member and add a property "requiresParticipation" with true/false values. does that make sense?

**Comment by SunderlandNRW** [comment]
> > ![image](https://user-images.githubusercontent.com/65600593/199494189-60e9bf2e-d5cd-478b-a64d-0658721436d4.png) ![image](https://user-images.githubusercontent.com/65600593/199666820-b4eee3d8-a9d0-4105-b6ff-1e47f3495ee1.png)
> > 
> > * Is "DoItTogetherEvent" the right expression?
> > * Is "Mitmachevent" the applicable expression?
> > * Especially for sports events, a distinction should be made between "watch Sport Event" and "Do sport yourself", as well as "event participation: yes / no".
> 
> if this "participating / watching" distinction is applicable to many event types, we could drop the MitmatchEvent enumeration member and add a property "requiresParticipation" with true/false values. does that make sense?

I think a "Mitmach-Event" is a typical family/kids event type. Maybe "requiresParticipation" true or false is a little too demanding? I suggested eventParticipation 3 comments up. Maybe we could include something like active participation to the enumeration?

**Comment by sumutcan** [comment]
> 
I personally like the ActiveParticipation as enumeration member. Definitely sounds better than DoItTogetherEvent.

**Comment by FabianBerner1** [comment]
> ![image](https://user-images.githubusercontent.com/65600593/199664632-60aa5a5d-47de-47a1-b8a2-9de332d9ed2d.png)
> 
> * Is a BikeTour in the sense of a guided bike tour a touristtrip or an event? Or is it even an offer?
> * Same with "city tour", "bus tour" or "harbour tour". It may be an event in the user context, technically an event and touristtrip or also an offer: how should it be implemented?
> * for further information please see: _"Request for Comments for RDS Erweiterungen des Typs TouristTrip und seiner Untertypen  02.02.2022 in [issue#8](https://github.com/ODTA/ds/issues/8)"_

I think an additional Subclass of Event is needed for these kinds of guided tours. A Guided Tour will always be an event of some sorts, so it would not be advisable to use the TouristTrip Domain for these, because a lot of information would have to be duplicated or referenced from another Event entry. The TouristTrip Type can still be used for tours that are not guided, and therefore don`t take place at one specific time and date or would have to be booked in advance.

I would propose to use the TouristTrip Class for unguided tours in the touristim domain and use a new subclass of Event: GuidedTour for guided tours, which are always events of some sort. 
With the kindOfEvent enumeration members: cityTour, natureAndLandscapeTour, parkTour, museumTour, studioAndWorkshopTour

**Comment by FabianBerner1** [comment]
For Tours like biketours, hiking tours, canoe tours, we there could be another subtype of Event called "tours" with the aforementioned enumeration members for kindOfEvent

**Comment by FabianBerner1** [comment]
Another subclass of Event named "customs & folklore" would be good to have, as these kinds of events can only be implicitly labeld through the eventTheme folklore at the moment.

**Comment by FabianBerner1** [comment]
Another Subclass of Event named "ship and boat trips" would be good to have too

**Comment by FabianBerner1** [comment]
As well as another new Subclass of Event named "wellness and health" these kind of event can only be mapped with EventTheme "Wellness" as of now, but there are many kinds of Events here so it would make sense to give them their own subclass

**Comment by FabianBerner1** [comment]
![image](https://user-images.githubusercontent.com/117816182/201955029-79b2ecae-9273-4ef0-9f6a-42aeeb089a4d.png)
I propose 2 more enumeration members for Festival instances: villageFestival and harvestFest

**Comment by FabianBerner1** [comment]
![image](https://user-images.githubusercontent.com/117816182/201956149-7faae6e4-c4c4-4571-9883-95ae278ab8b1.png)
I propose another enumeration member for foodEvent instances: Brunch

**Comment by FabianBerner1** [comment]
![image](https://user-images.githubusercontent.com/117816182/201956992-37385471-6852-4dec-b929-3e3a668d4048.png)
I propose 2 more enumeration members for saleEvent instances: regional market and exhibitor market

**Comment by FabianBerner1** [comment]
For TheaterEvent instances I propose the 3 new enumeration Members: kleinkunst (what is a fitting translation?), show and circus

**Comment by FabianBerner1** [comment]
![image](https://user-images.githubusercontent.com/117816182/201962988-9112ac08-3827-40e5-b33e-3c54e6b4a08f.png)
For educationEvent instances i propose to add 3 new enumeration members: arts and crafts, sport and health, culinary

**Comment by SunderlandNRW** [comment]
> > ![image](https://user-images.githubusercontent.com/65600593/199664632-60aa5a5d-47de-47a1-b8a2-9de332d9ed2d.png)
> > 
> > * Is a BikeTour in the sense of a guided bike tour a touristtrip or an event? Or is it even an offer?
> > * Same with "city tour", "bus tour" or "harbour tour". It may be an event in the user context, technically an event and touristtrip or also an offer: how should it be implemented?
> > * for further information please see: _"Request for Comments for RDS Erweiterungen des Typs TouristTrip und seiner Untertypen  02.02.2022 in [issue#8](https://github.com/ODTA/ds/issues/8)"_
> 
> I think an additional Subclass of Event is needed for these kinds of guided tours. A Guided Tour will always be an event of some sorts, so it would not be advisable to use the TouristTrip Domain for these, because a lot of information would have to be duplicated or referenced from another Event entry. The TouristTrip Type can still be used for tours that are not guided, and therefore don`t take place at one specific time and date or would have to be booked in advance.
> 
> I would propose to use the TouristTrip Class for unguided tours in the touristim domain and use a new subclass of Event: GuidedTour for guided tours, which are always events of some sort. With the kindOfEvent enumeration members: cityTour, natureAndLandscapeTour, parkTour, museumTour, studioAndWorkshopTour

I agree with adding "guided" as an enumeration to event type. But I think we should nevertheless add bike tour to a DS eventParticipation (e.g. Spectating, competiting or contest participating, cycling, walking, etc.) or part of eventNature (active etc.?). As a bike tour is not always guided. So guided and bike tour are two different DS.

**Comment by SunderlandNRW** [comment]
> 

But that is more a trip than an event?
Event types currently:
[BusinessEvent](https://schema.org/BusinessEvent)
[ChildrensEvent](https://schema.org/ChildrensEvent)
[ComedyEvent](https://schema.org/ComedyEvent)
[CourseInstance](https://schema.org/CourseInstance)
[DanceEvent](https://schema.org/DanceEvent)
[DeliveryEvent](https://schema.org/DeliveryEvent)
[EducationEvent](https://schema.org/EducationEvent)
[EventSeries](https://schema.org/EventSeries)
[ExhibitionEvent](https://schema.org/ExhibitionEvent)
[Festival](https://schema.org/Festival)
[FoodEvent](https://schema.org/FoodEvent)
[Hackathon](https://schema.org/Hackathon)
[LiteraryEvent](https://schema.org/LiteraryEvent)
[MusicEvent](https://schema.org/MusicEvent)
[PublicationEvent](https://schema.org/PublicationEvent)
[SaleEvent](https://schema.org/SaleEvent)
[ScreeningEvent](https://schema.org/ScreeningEvent)
[SocialEvent](https://schema.org/SocialEvent)
[SportsEvent](https://schema.org/SportsEvent)
[TheaterEvent](https://schema.org/TheaterEvent)
[VisualArtsEvent](https://schema.org/VisualArtsEvent)

Trip types currently:
[BoatTrip](https://schema.org/BoatTrip)
[BusTrip](https://schema.org/BusTrip)
[Flight](https://schema.org/Flight)
[TouristTrip](https://schema.org/TouristTrip)
[TrainTrip](https://schema.org/TrainTrip)

You probably mean a boart tour not trip.

**Comment by SunderlandNRW** [comment]
> 

Any thoughts on this?

**Comment by SunderlandNRW** [comment]
> > ![image](https://user-images.githubusercontent.com/65600593/199492993-d7453e05-b9c4-4e5f-aa38-176fb769166d.png) is "DanceClub" a separate event than a generic dance event? Any opinions?
> 
> I feel we need to clarify the difference (or intersections) between nature, theme and types (kindof). And what makes sense all together. Looking at the problem "DanceClub" as a type of event (kindof). The event type is DanceEvent. Why do we need more types (kindof)? Wouldn't these new types only be specifications of the existing Type DanceEvent? Properties like "DanceClub" are merely other specifications like those in Annex B (themes).
> 
> I would suggest combining the proposed DS odta:kindOfEvent and odta:theme, as most of the suggested "themes" in Annex B specify MusicEvent anyway. The new DS could be called odta:eventSpecification and list a combination of Annex A and B. An enumeration with minimum one to choose.
> 
> However I am not sure if we need to have separate DS odta:eventSpecification for every type of event? [BusinessEvent](https://schema.org/BusinessEvent) -> odta:eventSpecificationBusiness [ChildrensEvent](https://schema.org/ChildrensEvent) -> odta:eventSpecificationChildrens etc. Or is there a way to cluster a DS odta:eventSpecification with categories and subcategories?

Any thoughts on this?

**Comment by sumutcan** [comment]
# Intermediary Results

## 1 Introduction

Here is a "Zwischenbericht". It took some time for me to figure out the best way to represent this to ignite the further discussion. Here is a try. I'll go via referencing the sections in RC. The agreed aspects are marked with ✅ and the aspects that need further discussion with ⚠️ .
I gave my opinion as much as possible whether a recommendation makes sense from my point of view (marked bold). Of course there are still  certain things that needs to be discussed by domain experts.

## 2 Suggestions in RC

### 2.1 location property

✅  seems like it is accepted in its proposed form.

### 2.2 nature of event property

✅  no objections regarding representing it with the theme property (see below)

### 2.3. advancedBookingRequirement

✅  the usage of the property is agreed. 

⚠️  However, it is not clear yet if there should be any restrictions on the QuantativeValue type as the value type. One option is to use the value property only in the QuantitiveValue type with the Boolean range, so we can just say whether booking in advance is required or not. Other option is to allow more detailed specification such as how much time in advance should be booking be done (earliest and latest). @SunderlandNRW says they only have use cases fitting the first case. **Are there any other comments on this from other members?** I personally think the true / false value would be enough for the beginning.

### 2.4. theme property

✅  the usage of the property is agreed. 

⚠️ @SunderlandNRW suggested to use ActiveParticipation as canonical name for "Mitmach-Event" themed events. I agree with this. **I will accept this suggestion in the DraftDS, if there is no objection.**

⚠️ @SunderlandNRW recommends to have a way to specify the level of activity of an event that asks for participation (Mitmachevent). **I think this is currently covered with the usage of kindofEvent enumerations on SportsEvent and the theme enumerations. If something more detailed for this is needed, we can discuss in the next round of updates.**

⚠️ Other Enumeration members are not commented (Appendix B) so **for now it is assumed that they are satisfactory.**

### 2.5 kindOfEvent

⚠️@SunderlandNRW recommends to merge kindOfEvent with the theme property. **I do not agree to this as there can be cases both are needed (at least according to my intuition): kindOfEvent: CityFestival, theme: 90sMusic.** 

Most of the comments are regarding the enumeration members used as values for kindOfEvent. Here are the discussed points:

⚠️ Is DanceClub really an Event type? If yes, how is it different than a DanceEvent. As @SunderlandNRW pointed out there is a general confusion about themes and type of events. **Although I do not agree with merging the two, I agree with going through both lists of enumeration members and eliminate possible duplicates.** 
✅ MeetingOfMembers should be called GeneralAssembly, and Mitgliederversammlung in German
⚠️ Could not agree on a translation for Schützenfest (suggestions: Markmen's Festival, Rifle Association Festival)
✅ Illumination and Lichterfest difference is clear
✅ weiterbildung and fortbildung difference is clear
✅ CookingCompetition is Kochwettbewerb in German.
⚠️ not clear what Schiffsanlauf in English should be in tourism context. 
⚠️ there is a rather large discussion about kind of events that tours. @SunderlandNRW @FabianBerner1 and @CF-TMN bring up interesting points regarding where tourist trips and guided tours fit, what happens when they have offers? **I think the recommended TouristTripDS is modelled adressing all these points (including tours being events), I recommend moving the discussion about tours there. issue #8** 

⚠️ **I definitely agree with @SunderlandNRW that the list of enumeration members are too large to discuss here efficiently and effectively. Maybe we can use a polling tool like Mentimeter to identify the "most important ones (important for more than 50% of the participants)" to add in the first version DS. What do you think?** 

## 3 Newly suggested enumeration members

@FabianBerner1 makes several new enumeration member suggestions. all of them marked with ⚠️ as it needs to be decided whether they are necessary.

⚠️ customs and folklore is recommended as a new kind of event. Is there any reason that this should go beyond the Folklore theme?
⚠️ wellness and health is recommended as a new kind of event. Is there any reason that this should go beyond the Folklore theme?
⚠️ new kind of Festival enumeration members: VillageFest and HarvestFest
⚠️ new kind of FoodEvent enumeration members: Brunch
⚠️ new kind of SaleEvent enumeration members: RegionalMarket and ExhibitorMarket
⚠️ new kind of EducationEvent enumeration members: ArtsAndCraft, SportAndHealth, Culinary
⚠️ **the type recommended about tours should be discussed also in issue #8 .**
 
## 4 Conclusion

Please let me know if I missed anything from the discussion above. If you want to comment on a part of this Zwischenbericht, just copy and paste it with the "blockquote" functionality of Github. You can see it among the buttons in the toolbar on top of thecomment box (next to the italic button).

**Comment by sumutcan** [comment]
@SunderlandNRW @tomsievert @CF-TMN @eliaskaerle @FabianBerner1 any comments on the Zwischenbericht? I recommend we have a meeting after 9.01.2022 to discuss your final open questions so I can set up a draft DS?

**Comment by SunderlandNRW** [comment]
> @SunderlandNRW @tomsievert @CF-TMN @eliaskaerle @FabianBerner1 any comments on the Zwischenbericht? I recommend we have a meeting after 9.01.2022 to discuss your final open questions so I can set up a draft DS?

@sumutcan @sumutcan I'd be happy to take part in a short meeting. Anywhere between 10h and 13h on the 11.01. or from 14h onwards on the 12.01. would be good.

**Comment by CF-TMN** [comment]
> @SunderlandNRW @tomsievert @CF-TMN @eliaskaerle @FabianBerner1 any comments on the Zwischenbericht? I recommend we have a meeting after 9.01.2022 to discuss your final open questions so I can set up a draft DS?
@sumutcan From my point of view, it fit´s so far in the "Zwischenbericht" for this issue. But I'm also happy to participate in the meeting. The 11.01. (10-11 a.m. or 12-1 p.m.) or 12.01. (2-3 p.m.) would suit me. Until then, have a relaxing Christmas season and a good start in 2023!

**Comment by sumutcan** [comment]
@SunderlandNRW @CF-TMN I sent you an invite for 11.01.2023 10.00

**Comment by FabianBerner1** [comment]
> @SunderlandNRW @CF-TMN I sent you an invite for 11.01.2023 10.00

@sumutcan I would like to partake in the meeting too!

**Comment by sumutcan** [comment]
@FabianBerner1 please send me an email at umutcan.simsek [at] sti2.at

**Comment by sumutcan** [comment]
@eliaskaerle @tomsievert @SunderlandNRW @CF-TMN @FabianBerner1 

here is the draft ds merged with the RC #15 
https://semantify.it/list/7Kk-V4zwE?ds=lpJv_TwOa

I will make a google form for the enumeration members to vote for them seperately
